# Generated by Django 5.0.6 on 2024-06-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_payment_options_alter_payment_paid_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="date_payment",
            field=models.DateField(auto_now_add=True, verbose_name="дата оплаты"),
        ),
    ]
