# Generated by Django 5.0.6 on 2024-07-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_payment_date_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='id_session',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='id сессии'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_link',
            field=models.URLField(blank=True, max_length=350, null=True, verbose_name='ссылка на оплату'),
        ),
    ]
