# Generated by Django 5.0.6 on 2024-07-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_payment_id_session_payment_payment_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_link',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='ссылка на оплату'),
        ),
    ]
