# Generated by Django 5.0.6 on 2024-07-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_alter_subscription_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='amount',
            field=models.IntegerField(default=1000, verbose_name='цена'),
        ),
    ]
