# Generated by Django 5.0.6 on 2024-07-04 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_lesson_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='amount',
        ),
    ]
